### ISSUE TITLE
visit method not working with external url

### ISSUE THREAD

**Issue by bikashp** [smparkes/capybara-envjs#20]
Simple test using visit method seems to fail while using envjs driver. Works fine with default driver.

When I google
Then I should see "2010 Google"

When /^I google$/ do 
  visit "http://www.google.com" \n
end

Running feature fails with "false is not true. (Test::Unit::AssertionFailedError)" message.

Also when using full url (eg. http://www.google.com/webhp), it errors out with "No route matches "/webhp" with {:method=>:get} (ActionController::RoutingError)" message

**Comment by smparkes** [comment]
Can you push a repo I can try?

Do you get any envjs error when you do this? Google has enough messy JS on their page that it breaks envjs. At one point I tried to track down the cause, but it's all minifed stuff which which is just painful to deal with.

**Comment by bikashp** [comment]
I made simple changes to http://github.com/schlick/capybara-demo to test visit method on external link using envjs. Changes i made are already posted on issue. 

Error/failure message:
      false is not true. (Test::Unit::AssertionFailedError)
      /usr/local/lib/ruby/1.8/test/unit/assertions.rb:48:in `assert_block'
      /usr/local/lib/ruby/1.8/test/unit/assertions.rb:500:in`_wrap_assertion'
      /usr/local/lib/ruby/1.8/test/unit/assertions.rb:46:in `assert_block'
      /usr/local/lib/ruby/1.8/test/unit/assertions.rb:63:in`assert'
      /usr/local/lib/ruby/1.8/test/unit/assertions.rb:495:in `_wrap_assertion'
      /usr/local/lib/ruby/1.8/test/unit/assertions.rb:61:in`assert'
     ./features/step_definitions/web_steps.rb:104
      ./features/step_definitions/web_steps.rb:13:in `with_scope'
      ./features/step_definitions/web_steps.rb:100:in`/^(?:|I )should see "([^\"]_)"(?: within
        "([^\"]_)")?$/'

There is envjs warning message also:
{ENVJS} could not load script http://www.google.com/javascripts/jquery-1.4.2.min.js?1276247318: 
XML tag name mismatch (expected meta)

I think it is still assuming that link as local rails app link and trying to load jquery and application 
js file. If i change url to http://www.google.com/webhp, it gives "No route matches "/webhp" with {:method=>:get} (ActionController::RoutingError)" message.

**Comment by smparkes** [comment]
Cool. This is should be able to make some sense of. As long as it's not tortured JS ...

**Comment by smparkes** [comment]
Is this still an issue? If so, can you tell me how to replicate it? I did the normal rake test and cucumber tasks and they succeed.
